//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_Balance
    {
        public int BalanceID { get; set; }
        public int PaymentID { get; set; }
        public int ReceptionID { get; set; }
        public int DocumentsTypeID { get; set; }
        public decimal ShouldAmount { get; set; }
        public decimal OptimalAmount { get; set; }
        public decimal CollectionAmount { get; set; }
        public string Remark { get; set; }
        public int BalanceStateID { get; set; }
        public string BusinessNum { get; set; }
    }
}
