//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_Outbound
    {
        public int OutboundID { get; set; }
        public Nullable<int> DocumentsTypeID { get; set; }
        public int SalesCustomerID { get; set; }
        public string Stockremoval { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<decimal> Tradeprice { get; set; }
        public string Processingman { get; set; }
        public Nullable<bool> Reviewwhet { get; set; }
        public string Therevie { get; set; }
        public Nullable<System.DateTime> Auditdates { get; set; }
        public string SalesorderNum { get; set; }
        public Nullable<decimal> Theamount { get; set; }
        public string Remark { get; set; }
        public string DocuState { get; set; }
        public Nullable<int> BalanceStateID { get; set; }
    }
}
