//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_ProBalance
    {
        public int ProBalanceID { get; set; }
        public int SuppliersID { get; set; }
        public string Receipt { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> CurrentMany { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Operator { get; set; }
        public bool ToAudit { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string Remark { get; set; }
        public int PaymentID { get; set; }
    }
}
