//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_Procurement
    {
        public int ProcurementID { get; set; }
        public int SuppliersID { get; set; }
        public int UserID { get; set; }
        public int WarehouseID { get; set; }
        public string IndentNumber { get; set; }
        public string Maker { get; set; }
        public System.DateTime MakerDate { get; set; }
        public Nullable<System.DateTime> DeliveryDeadline { get; set; }
        public Nullable<decimal> Handsel { get; set; }
        public Nullable<bool> ToAudit { get; set; }
        public string Auditer { get; set; }
        public Nullable<System.DateTime> AuditerDate { get; set; }
        public string Remark { get; set; }
        public string Documents { get; set; }
        public Nullable<decimal> Aamount { get; set; }
    }
}
