//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_Predate
    {
        public int PredateID { get; set; }
        public int CarderID { get; set; }
        public string VehicleType { get; set; }
        public int RepairID { get; set; }
        public string PredateNum { get; set; }
        public System.DateTime OpenDate { get; set; }
        public string MaintenanceNum { get; set; }
        public string CarNum { get; set; }
        public string Owner { get; set; }
        public string Telephone { get; set; }
        public string Contacts { get; set; }
        public string CarMasterPhone { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> ToAudit { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Receivable { get; set; }
        public string Describe { get; set; }
        public Nullable<bool> ToTransferOrder { get; set; }
        public System.DateTime MaintainData { get; set; }
        public Nullable<decimal> DeserveMoney { get; set; }
        public string CustomerNum { get; set; }
    }
}
