//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_ReturnForm
    {
        public int ReturnFormID { get; set; }
        public int SuppliersID { get; set; }
        public int WarehouseID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> DocumentsTypeID { get; set; }
        public Nullable<int> BalanceStateID { get; set; }
        public string ReturnNumber { get; set; }
        public string Maker { get; set; }
        public Nullable<System.DateTime> SingleDate { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> ToAudit { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> SheetDate { get; set; }
        public string IncomingNumber { get; set; }
    }
}
