//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_Reception
    {
        public int ReceptionID { get; set; }
        public Nullable<int> DocumentStateID { get; set; }
        public Nullable<int> BalanceStateID { get; set; }
        public string VehicleType { get; set; }
        public string Carder { get; set; }
        public int RepairID { get; set; }
        public Nullable<int> CustomerSouID { get; set; }
        public string CarNum { get; set; }
        public string Mileage { get; set; }
        public string Owner { get; set; }
        public string Address { get; set; }
        public string OilQuantity { get; set; }
        public string OwnerTele { get; set; }
        public string EngineNum { get; set; }
        public string Repairman { get; set; }
        public string SelfCoding { get; set; }
        public string FrameNum { get; set; }
        public string RepairmanTele { get; set; }
        public Nullable<System.DateTime> FactoryDate { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<bool> ToAudit { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Describe { get; set; }
        public string MaintenanceNum { get; set; }
        public string CollageState { get; set; }
        public Nullable<bool> ToSendWork { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<decimal> MaintenAmount { get; set; }
        public Nullable<bool> ToCompletion { get; set; }
        public string CustomerNum { get; set; }
    }
}
