//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_SalesReturnl
    {
        public int SalesReturnlID { get; set; }
        public Nullable<int> DocumentsTypeID { get; set; }
        public Nullable<int> BalanceStateID { get; set; }
        public int SalesCustomerID { get; set; }
        public string Oddseats { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string Returnmode { get; set; }
        public string Operator { get; set; }
        public Nullable<bool> ToAudit { get; set; }
        public string Auditor { get; set; }
        public Nullable<decimal> Theamount { get; set; }
        public string Stockremoval { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string Remark { get; set; }
    }
}
