//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_ThreePacks
    {
        public int ThreePacksID { get; set; }
        public int ThreePacksDetailID { get; set; }
        public string InsuranceNum { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
        public string ClaimsStaff { get; set; }
        public bool ToTicket { get; set; }
        public string SelfCoding { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> ToAudit { get; set; }
        public string Operator { get; set; }
    }
}
