//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_User
    {
        public int UserID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string UserNum { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> ToUse { get; set; }
    }
}
