//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QXQPEntities : DbContext
    {
        public QXQPEntities()
            : base("name=QXQPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PW_Balance> PW_Balance { get; set; }
        public virtual DbSet<PW_Collage> PW_Collage { get; set; }
        public virtual DbSet<PW_Incoming> PW_Incoming { get; set; }
        public virtual DbSet<PW_Insurance> PW_Insurance { get; set; }
        public virtual DbSet<PW_Jurisdiction> PW_Jurisdiction { get; set; }
        public virtual DbSet<PW_Outbound> PW_Outbound { get; set; }
        public virtual DbSet<PW_Predate> PW_Predate { get; set; }
        public virtual DbSet<PW_ProBalance> PW_ProBalance { get; set; }
        public virtual DbSet<PW_Procurement> PW_Procurement { get; set; }
        public virtual DbSet<PW_Reception> PW_Reception { get; set; }
        public virtual DbSet<PW_Restock> PW_Restock { get; set; }
        public virtual DbSet<PW_ReturnForm> PW_ReturnForm { get; set; }
        public virtual DbSet<PW_SalBalance> PW_SalBalance { get; set; }
        public virtual DbSet<PW_Salesorder> PW_Salesorder { get; set; }
        public virtual DbSet<PW_SalesReturnl> PW_SalesReturnl { get; set; }
        public virtual DbSet<PW_ThreePacks> PW_ThreePacks { get; set; }
        public virtual DbSet<PW_User> PW_User { get; set; }
        public virtual DbSet<SYS_BalanceState> SYS_BalanceState { get; set; }
        public virtual DbSet<SYS_Carder> SYS_Carder { get; set; }
        public virtual DbSet<SYS_ClaimCom> SYS_ClaimCom { get; set; }
        public virtual DbSet<SYS_CollageDetai> SYS_CollageDetai { get; set; }
        public virtual DbSet<SYS_CustomerLevel> SYS_CustomerLevel { get; set; }
        public virtual DbSet<SYS_CustomerSou> SYS_CustomerSou { get; set; }
        public virtual DbSet<SYS_CustomerType> SYS_CustomerType { get; set; }
        public virtual DbSet<SYS_Department> SYS_Department { get; set; }
        public virtual DbSet<SYS_Dispatch> SYS_Dispatch { get; set; }
        public virtual DbSet<SYS_DocumentState> SYS_DocumentState { get; set; }
        public virtual DbSet<SYS_DocumentsType> SYS_DocumentsType { get; set; }
        public virtual DbSet<SYS_Expenses> SYS_Expenses { get; set; }
        public virtual DbSet<SYS_FittingsInfo> SYS_FittingsInfo { get; set; }
        public virtual DbSet<SYS_FittingsType> SYS_FittingsType { get; set; }
        public virtual DbSet<SYS_ForeMan> SYS_ForeMan { get; set; }
        public virtual DbSet<SYS_InsuranceCom> SYS_InsuranceCom { get; set; }
        public virtual DbSet<SYS_InsuranceDetail> SYS_InsuranceDetail { get; set; }
        public virtual DbSet<SYS_InsuranceSpe> SYS_InsuranceSpe { get; set; }
        public virtual DbSet<SYS_Inventory> SYS_Inventory { get; set; }
        public virtual DbSet<SYS_Maintainability> SYS_Maintainability { get; set; }
        public virtual DbSet<SYS_Maintenance> SYS_Maintenance { get; set; }
        public virtual DbSet<SYS_MaintenanceCrew> SYS_MaintenanceCrew { get; set; }
        public virtual DbSet<SYS_MaintenanceCus> SYS_MaintenanceCus { get; set; }
        public virtual DbSet<SYS_Modular> SYS_Modular { get; set; }
        public virtual DbSet<SYS_ModularType> SYS_ModularType { get; set; }
        public virtual DbSet<SYS_OutboundDetails> SYS_OutboundDetails { get; set; }
        public virtual DbSet<SYS_Payment> SYS_Payment { get; set; }
        public virtual DbSet<SYS_PreOtherCostDetail> SYS_PreOtherCostDetail { get; set; }
        public virtual DbSet<SYS_PreProductDetail> SYS_PreProductDetail { get; set; }
        public virtual DbSet<SYS_PreRepairItemDetail> SYS_PreRepairItemDetail { get; set; }
        public virtual DbSet<SYS_ProBalancetDetail> SYS_ProBalancetDetail { get; set; }
        public virtual DbSet<SYS_ProcurementDetail> SYS_ProcurementDetail { get; set; }
        public virtual DbSet<SYS_RecOtherCostDetail> SYS_RecOtherCostDetail { get; set; }
        public virtual DbSet<SYS_RecProductDetail> SYS_RecProductDetail { get; set; }
        public virtual DbSet<SYS_RecRepairItemDetail> SYS_RecRepairItemDetail { get; set; }
        public virtual DbSet<SYS_Region> SYS_Region { get; set; }
        public virtual DbSet<SYS_Repair> SYS_Repair { get; set; }
        public virtual DbSet<SYS_RepairClass> SYS_RepairClass { get; set; }
        public virtual DbSet<SYS_RepairItem> SYS_RepairItem { get; set; }
        public virtual DbSet<SYS_RepairMan> SYS_RepairMan { get; set; }
        public virtual DbSet<SYS_RestockDetail> SYS_RestockDetail { get; set; }
        public virtual DbSet<SYS_ReturnFormDetail> SYS_ReturnFormDetail { get; set; }
        public virtual DbSet<SYS_SalBalancetDetail> SYS_SalBalancetDetail { get; set; }
        public virtual DbSet<SYS_SalesCustomer> SYS_SalesCustomer { get; set; }
        public virtual DbSet<SYS_SalesorderDetail> SYS_SalesorderDetail { get; set; }
        public virtual DbSet<SYS_SalesReturnDetails> SYS_SalesReturnDetails { get; set; }
        public virtual DbSet<SYS_Subject> SYS_Subject { get; set; }
        public virtual DbSet<SYS_Suppliers> SYS_Suppliers { get; set; }
        public virtual DbSet<SYS_SystemUnit> SYS_SystemUnit { get; set; }
        public virtual DbSet<SYS_ThreePacksDetail> SYS_ThreePacksDetail { get; set; }
        public virtual DbSet<SYS_UserType> SYS_UserType { get; set; }
        public virtual DbSet<SYS_VehicleType> SYS_VehicleType { get; set; }
        public virtual DbSet<SYS_Warehouse> SYS_Warehouse { get; set; }
        public virtual DbSet<SYS_WarehousingDetail> SYS_WarehousingDetail { get; set; }
    }
}
