//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SalBalancetDetail
    {
        public int SalBalancetDetailID { get; set; }
        public Nullable<int> SalBalanceID { get; set; }
        public Nullable<int> DocumentsTypeID { get; set; }
        public Nullable<int> BalanceStateID { get; set; }
        public Nullable<bool> ToCleared { get; set; }
        public string SingleNumber { get; set; }
        public Nullable<System.DateTime> DocumentsDate { get; set; }
        public Nullable<decimal> ShouldAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> SuperioAmountr { get; set; }
        public Nullable<decimal> ThisSuperioAmountr { get; set; }
        public Nullable<decimal> ThisShouldAmount { get; set; }
    }
}
