//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CollageDetai
    {
        public int CollageDetaiID { get; set; }
        public int MaintainabilityID { get; set; }
        public int WarehouseID { get; set; }
        public int CollageID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public string Position { get; set; }
        public string VehicleType { get; set; }
        public string FittingsName { get; set; }
        public string FittingsCode { get; set; }
        public string FittingsSpec { get; set; }
        public string SystemUnit { get; set; }
    }
}
