//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RecOtherCostDetail
    {
        public int ReceptionID { get; set; }
        public int ExpensesID { get; set; }
        public int RecOtherCostDetailID { get; set; }
        public decimal Amount { get; set; }
        public decimal Discount { get; set; }
        public decimal AmountPaid { get; set; }
        public string Remark { get; set; }
    }
}
