//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_InsuranceDetail
    {
        public int InsuranceDetailID { get; set; }
        public int ReceptionID { get; set; }
        public Nullable<int> InsuranceComID { get; set; }
        public string ReportNum { get; set; }
        public string PolicyNum { get; set; }
        public Nullable<decimal> PolicyMoney { get; set; }
        public Nullable<decimal> InsuranceMoney { get; set; }
    }
}
