//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MaintenanceCus
    {
        public int MaintenanceCusID { get; set; }
        public string VehicleType { get; set; }
        public int InsuranceComID { get; set; }
        public int InsuranceSpeID { get; set; }
        public int DepartmentID { get; set; }
        public int CarderID { get; set; }
        public int CustomerTypeID { get; set; }
        public int CustomerLevelID { get; set; }
        public int RegionID { get; set; }
        public int CustomerSouID { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MobilePhone { get; set; }
        public string IdNumber { get; set; }
        public string LicenseCode { get; set; }
        public string EngineNum { get; set; }
        public string FrameNum { get; set; }
        public string RepairMan { get; set; }
        public string RepairTele { get; set; }
        public Nullable<System.DateTime> InitialStartDate { get; set; }
        public Nullable<System.DateTime> InitialEndDate { get; set; }
        public string Address { get; set; }
        public string CustomerNum { get; set; }
        public Nullable<System.DateTime> DriveDate { get; set; }
        public Nullable<System.DateTime> DrivingDate { get; set; }
        public string InputPerson { get; set; }
    }
}
