//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Suppliers
    {
        public int SuppliersID { get; set; }
        public string SuppliersFirm { get; set; }
        public string SuppliersName { get; set; }
        public string PinYinCode { get; set; }
        public string MainBusiness { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
        public string TelePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Facsimile { get; set; }
        public string Mailbox { get; set; }
        public string Url { get; set; }
        public string OpenBank { get; set; }
        public string TaxNumber { get; set; }
        public string InputPerson { get; set; }
        public string StorageAdd { get; set; }
        public string StorageTele { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> ToDeactivate { get; set; }
        public string BalanceMode { get; set; }
        public Nullable<decimal> DeserveMoney { get; set; }
    }
}
