//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PreRepairItemDetail
    {
        public int PreRepairItemDetailID { get; set; }
        public int RepairItemID { get; set; }
        public int PredateID { get; set; }
        public int MaintainabilityID { get; set; }
        public decimal RepairCharge { get; set; }
        public decimal Discount { get; set; }
        public decimal AmountPaid { get; set; }
        public string Remark { get; set; }
    }
}
