//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QXQPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Inventory
    {
        public int InventoryID { get; set; }
        public int WarehouseID { get; set; }
        public string FittingsCode { get; set; }
        public string FittingsName { get; set; }
        public string VehicleType { get; set; }
        public string SystemUnit { get; set; }
        public Nullable<decimal> InvenQuan { get; set; }
        public Nullable<decimal> NewIntake { get; set; }
        public Nullable<decimal> WholePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> MinInventory { get; set; }
        public string Position { get; set; }
        public string FittingsType { get; set; }
    }
}
